### ISSUE TITLE
Is there a printer?

### ISSUE THREAD

**Issue by TyOverby** [astrada/ocaml-css-parser#10]
Hi there!  I've really enjoyed using the parser so far! 

My goal is to parse a css file, do some transformations on it, and then turn it back into a string.  That is to say, implement a function from `Stylesheet.t -> string`. Do you happen to know if someone has already done this?

Thanks!

**Comment by astrada** [comment]
No, sorry. There is only https://github.com/astrada/ocaml-css-parser/blob/master/test/css_fmt_printer.ml that I use for testing, but it doesn't do pretty printing and I'm not sure if the output is valid CSS.

**Comment by TyOverby** [comment]
I was looking at some other (closed) issues on this project and saw that @Chimrod appears to have written a minimiser + concatenator.  @Chimrod: are these published anywhere, and would you mind if I used them?

**Comment by Chimrod** [comment]
Yes, the code is right here : https://git.chimrod.com/css_lib.git/tree/lib/print.ml

**Comment by TyOverby** [comment]
@Chimrod lovely, thank you so much!  If it wouldn't be too much to ask, could you add a license the code?  I'm trying to do my best to not run afoul of any copyright issues, and making sure that I'm following the law would put my mind at ease.

**Comment by Chimrod** [comment]
Sure. Not yet, but I'll add the MIT Licence with week-end.

**Comment by Chimrod** [comment]
Hi ! I've updated the repo, use it as you want !
