### ISSUE TITLE
Consider publishing to OPAM

### ISSUE THREAD

**Issue by dylanirlbeck** [astrada/ocaml-css-parser#5]
This recently popped into my head, but have you thought about publishing this library to OPAM? For my project I basically just coped over the code but this seems a bit redundant, especially if you create new features or bug fixes.

I'd be happy to help if possible, thanks again for doing this!

EDIT: I tried `esy add @opam/ocaml-css-parser` and the install was not successful, which is why I'm raising the issue.

**Comment by astrada** [comment]
I published it a couple of days ago (http://opam.ocaml.org/packages/css-parser/), but the opam name is `css-parser`, because the guidelines about naming packages discourage names that contain ocaml (it would be redundant).

**Comment by dylanirlbeck** [comment]
Nice, thanks!
