### ISSUE TITLE
Enhancement: Add a .ocamlformat file to project root

### ISSUE THREAD

**Issue by dylanirlbeck** [astrada/ocaml-css-parser#7]
This is kind of a developer feature request, but when using the project locally my editor (Vim) was causing all sorts of formatting-related changes that I didn't want to be included in my pull request. I think it'd be a good idea to either add a `.ocamlformat` file to the project root to enforce some standards for developers of this library, or enforce consistent formatting some other way.

Just a thought! Thanks.

**Comment by astrada** [comment]
Good idea!
