### ISSUE TITLE
Get rid of compiler-lib

### ISSUE THREAD

**Issue by Chimrod** [astrada/ocaml-css-parser#9]
# The problem

When compiling a project with js_of_ocaml a very minimal example: [(see attachment)](https://github.com/astrada/ocaml-css-parser/files/5934796/empty_js.zip)

dune file

```
(executable
 (name empty)
 (libraries 
   css-parser
   )
 (modes js)
 (preprocess (pps js_of_ocaml-ppx))
 (link_flags (:standard -no-check-prims))
 )
```

and with this code :

```ocaml
let () = ()
```

the generated output is near 1Mb when enabling all the optimisations. This is caused by compiler-lib dependency, which hold mutable definition in the top level and cannot be optimized.

# Rewriting Location

Compiler-lib is not required. Only the structure Location is used. A simple module with this minimal implementation in enougth for reducing the size of the generated javascript to 14ko!

```ocam
type t = {
  loc_start : Lexing.position;
  loc_end : Lexing.position;
  loc_ghost : bool;
}

let none =
  { loc_start = Lexing.dummy_pos
  ; loc_end = Lexing.dummy_pos
  ; loc_ghost = true
  }

let  register_error_of_exn _ = ()

let error ~loc ?(sub=[]) _ =
  let _ = loc
  and _ = sub in
  ()
```

# Points to clarify

I'm not sure how the function `register_error_of_exn` is used inside the parser, and this minimal implemation should be completed on this point.

There is also a change in the libraries using css-parser, as they will have to use `Css-parser.Location` module instead of `Location` (as the module become a part of the library and not a top level module anymore), but this should be transparent if the code open the `Css-parser` before.

If you are ok with this change, I can open a pull request with the changes, and let you review and integrate them if you are ok with them. (with your help to understand how `register_error_of_exn` works)

**Comment by astrada** [comment]
Unfortunately, I think that removing the error reporting functionality of the `Location` module reduces the usefulness of the parser if integrated in a ppx. For example, I'm using the parser in a ppx that integrates seamlessly with the compiler tools and merlin, like this: https://github.com/astrada/ppx_bs_css#what-you-get

**Comment by Chimrod** [comment]
Oh I see. Indeed, this is required if you want to build it in a ppx. I did not took this point in consideration.

Is it possible to functorize the library and use Location.t as a type in the functor ?

**Comment by Chimrod** [comment]
I have tried to play a bit with parametrization in Menhir, but this requires too much modifications in the code. I'll close the issue for now.

**Comment by astrada** [comment]
OK, thanks.
